version: 2
jobs:
  build:
    docker:
      - image: nomaddo/cross-rpi
    steps:
      - checkout
      - run:
          name: download header
          command: git clone https://github.com/doe300/VC4CLStdLib.git VC4CLStdLib && cd VC4CLStdLib && cmake . && make install && cd ..
      - run:
          name: configure
          # Use the libLLVM of the default LLVM/CLang, disable search for SPIRV-LLVM
#          command: cmake . -DCROSS_COMPILE=ON -DBUILD_TESTING=ON -DLLVMLIB_FRONTEND=ON -DSPIRV_FRONTEND=OFF -DSPIRV_COMPILER_ROOT=/tmp/
          command: cmake . -DCROSS_COMPILE=ON -DBUILD_TESTING=ON
      - run:
          name: make
          command: make -j2
      - run:
          name: deb-packing
          command: cpack -G DEB && cpack -G DEB --config ./VC4CLStdLib/CPackConfig.cmake
      - run:
          name: list-dependencies
          command: ldd build/libVC4CC.so.0.4
      - store_artifacts:
          path: build/libVC4CC.so.0.4
          distination: libVC4CC.so.0.4
      - store_artifacts:
          path: build/VC4C
          distination: VC4C
      - store_artifacts:
          path: build/test/TestVC4C
          distination: TestVC4C
      - store_artifacts:
          path: vc4c-0.4-Linux.deb
          distination: vc4c-0.4-Linux.deb
      - store_artifacts:
          path: vc4cl-stdlib-0.4-Linux.deb
          distination: vc4cl-stdlib-0.4-Linux.deb
